# Generated by Django 2.1.2 on 2018-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('between_street', models.CharField(max_length=200)),
                ('cbu', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
