# Generated by Django 2.1.2 on 2018-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='alumonos',
            new_name='alumno',
        ),
        migrations.AlterField(
            model_name='grupos',
            name='mes',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], db_index=True, max_length=1),
        ),
    ]
