# Generated by Django 2.0.1 on 2018-10-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='street',
        ),
    ]
