# Generated by Django 2.1.2 on 2018-11-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turno',
            new_name='Turnos',
        ),
    ]
