# Generated by Django 2.1.2 on 2018-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0002_auto_20181102_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(help_text='Id único para transportista ', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('entre_calle', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('cbu', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Transportista',
            },
        ),
    ]
