# Generated by Django 2.1.2 on 2018-10-29 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0002_remove_transportista_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('between_street', models.CharField(max_length=200)),
                ('cbu', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para para este movimiento en particular', primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_move', models.CharField(help_text='Tipo movimiento del transportista', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Transportista',
        ),
        migrations.AddField(
            model_name='carrierroute',
            name='id_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.MoveType'),
        ),
    ]
