# Generated by Django 2.1.2 on 2018-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0002_auto_20181115_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruposalumno',
            name='profesor',
        ),
        migrations.AddField(
            model_name='gruposalumno',
            name='grupo',
            field=models.ManyToManyField(to='app_natagua.Grupos'),
        ),
    ]
