# Generated by Django 2.1.2 on 2018-11-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0002_auto_20181119_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoAlumnosPresentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ManyToManyField(to='app_natagua.Alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Grupos')),
            ],
            options={
                'verbose_name_plural': 'ListadoAlumnosPresente',
            },
        ),
    ]
