# Generated by Django 2.1.2 on 2018-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0003_listadoalumnospresentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadoalumnospresentes',
            old_name='alumno',
            new_name='alumnos',
        ),
    ]
