# Generated by Django 2.1.2 on 2018-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0003_auto_20181115_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'verbose_name_plural': 'Grupo'},
        ),
        migrations.AlterModelOptions(
            name='gruposalumno',
            options={'verbose_name_plural': 'GrupoAlumnos'},
        ),
        migrations.AddField(
            model_name='gruposalumno',
            name='alumonos',
            field=models.ManyToManyField(to='app_natagua.Alumno'),
        ),
    ]
