# Generated by Django 2.1.2 on 2018-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0003_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='dni',
            field=models.CharField(default='', max_length=25),
        ),
    ]
