# Generated by Django 2.1.2 on 2018-10-29 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0004_carrierroute_date_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único el estudiante', primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('between_street', models.CharField(max_length=200)),
                ('cbu', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único el profesor', primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('between_street', models.CharField(max_length=200)),
                ('cbu', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único del tutor del estudiante', primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('between_street', models.CharField(max_length=200)),
                ('cbu', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la carrier', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.TutorRelationship'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.TeacherType'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.Tutor'),
        ),
    ]
