# Generated by Django 2.1.2 on 2018-10-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0005_auto_20181029_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrierroute',
            old_name='id_carrier',
            new_name='move_type',
        ),
        migrations.AddField(
            model_name='carrierroute',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.Carrier'),
        ),
    ]
