# Generated by Django 2.1.2 on 2018-11-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0006_listadoalumnospresentes_presente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadoalumnospresentes',
            name='presente',
        ),
    ]
