# Generated by Django 2.1.2 on 2018-10-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0006_auto_20181029_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='carrier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.CarrierType'),
        ),
    ]
