# Generated by Django 2.1.2 on 2018-11-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0007_remove_listadoalumnospresentes_presente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cuota', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('matricula', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pre_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pago_parcial', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('faltante', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('forma_pago', models.CharField(choices=[(1, 'Efectivo'), (2, 'CBU'), (3, 'Factura')], db_index=True, max_length=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Listado_pagos',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listadopagos',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Alumno'),
        ),
        migrations.AddField(
            model_name='listadopagos',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Complejo'),
        ),
        migrations.AddField(
            model_name='listadopagos',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Turnos'),
        ),
    ]
