# Generated by Django 2.1.2 on 2018-10-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0007_carrier_carrier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriertype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
