# Generated by Django 2.1.2 on 2018-11-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0007_auto_20181107_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Localidad'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Provincia'},
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provincia_localidad', to='app_natagua.Provincia'),
        ),
    ]
