# Generated by Django 2.1.2 on 2018-11-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0008_auto_20181107_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('id_provincia', 'id')},
        ),
    ]
