# Generated by Django 2.1.2 on 2018-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0008_auto_20181130_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadopagos',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
