# Generated by Django 2.1.2 on 2018-10-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0008_auto_20181029_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriertype',
            options={'verbose_name_plural': 'Tipo de Transportista'},
        ),
    ]
