# Generated by Django 2.1.2 on 2018-10-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0009_auto_20181029_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name_plural': 'Transportista'},
        ),
        migrations.AlterModelOptions(
            name='carrierroute',
            options={'verbose_name_plural': 'Transportista Ruta'},
        ),
        migrations.AlterModelOptions(
            name='movetype',
            options={'verbose_name_plural': 'Movimiento Transportista'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Profesor'},
        ),
        migrations.AlterModelOptions(
            name='teachertype',
            options={'verbose_name_plural': 'Tipo profesor'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name_plural': 'Tutor del Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='tutorrelationship',
            options={'verbose_name_plural': 'Tutor Relación'},
        ),
    ]
