# Generated by Django 2.1.2 on 2018-11-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0009_auto_20181107_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportista_localidad', to='app_natagua.Localidad'),
        ),
        migrations.AddField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportista_provincia', to='app_natagua.Provincia'),
        ),
    ]
