# Generated by Django 2.1.2 on 2018-11-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0009_listadopagos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('porcentage', models.CharField(blank=True, max_length=3, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('expiracion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Promocion',
            },
        ),
    ]
