# Generated by Django 2.1.2 on 2018-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0010_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='ombre',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
