# Generated by Django 2.1.2 on 2018-10-31 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0010_auto_20181029_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriertype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la carrier', primary_key=True, serialize=False),
        ),
    ]
