# Generated by Django 2.1.2 on 2018-11-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0011_promocion_ombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='ombre',
            new_name='nombre',
        ),
    ]
