# Generated by Django 2.1.2 on 2018-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0011_auto_20181108_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='celular',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
