# Generated by Django 2.1.2 on 2018-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0012_auto_20181031_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriertype',
            name='id',
            field=models.AutoField(help_text='Id único para tipo de transportista ', primary_key=True, serialize=False),
        ),
    ]
