# Generated by Django 2.1.2 on 2018-11-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0012_auto_20181130_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='porcentage',
            new_name='porcentaje',
        ),
    ]
