# Generated by Django 2.1.2 on 2018-10-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0013_auto_20181031_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.AutoField(help_text='Id único para transportista ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrierroute',
            name='id',
            field=models.AutoField(help_text='Id único para ruta de  transportista ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movetype',
            name='id',
            field=models.AutoField(help_text='Id único tipo de movimiento ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(help_text='Id único estudiante ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(help_text='Id único para profesor ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachertype',
            name='id',
            field=models.AutoField(help_text='Id único tipo de profesor ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.AutoField(help_text='Id único tutor ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutorrelationship',
            name='id',
            field=models.AutoField(help_text='Id único  para tutor relación', primary_key=True, serialize=False),
        ),
    ]
