# Generated by Django 2.1.2 on 2018-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0013_auto_20181130_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
