# Generated by Django 2.1.2 on 2018-11-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0013_auto_20181108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportista_localidad', to='app_natagua.Localidad'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportista_provincia', to='app_natagua.Provincia'),
        ),
    ]
