# Generated by Django 2.1.2 on 2018-12-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0014_promocion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_expiracion',
            field=models.DateTimeField(null=True),
        ),
    ]
