# Generated by Django 2.1.2 on 2018-11-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0014_auto_20181109_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_localidad', to='app_natagua.Provincia'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportista_localidad', to='app_natagua.Localidad'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportista_provincia', to='app_natagua.Provincia'),
        ),
    ]
