# Generated by Django 2.1.2 on 2018-11-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0015_auto_20181109_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Provincia'),
        ),
    ]
