# Generated by Django 2.1.2 on 2018-10-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0016_auto_20181031_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_custom',
        ),
    ]
