# Generated by Django 2.1.2 on 2018-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0016_auto_20181109_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='id_provincia',
        ),
        migrations.AddField(
            model_name='transportista',
            name='id_provincia',
            field=models.ManyToManyField(to='app_natagua.Provincia'),
        ),
    ]
