# Generated by Django 2.1.2 on 2018-12-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0017_auto_20181201_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadopagos',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Promocion'),
        ),
    ]
