# Generated by Django 2.1.2 on 2018-11-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0017_auto_20181109_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_natagua.Localidad'),
        ),
    ]
