# Generated by Django 2.1.2 on 2018-11-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0018_auto_20181109_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_natagua.Localidad'),
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='id_provincia',
        ),
        migrations.AddField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportista_provincia', to='app_natagua.Provincia'),
        ),
    ]
