# Generated by Django 2.1.2 on 2018-12-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0018_listadopagos_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_natagua.ListadoPagos')),
            ],
            options={
                'verbose_name_plural': 'FacturaPagos',
            },
        ),
    ]
