# Generated by Django 2.1.2 on 2018-11-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0019_auto_20181109_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id_localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='app_natagua.Localidad'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='app_natagua.Provincia'),
        ),
    ]
