# Generated by Django 2.1.2 on 2018-11-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0020_auto_20181109_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
