# Generated by Django 2.1.2 on 2019-07-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0020_auto_20181204_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadopagos',
            name='promocion',
        ),
        migrations.AddField(
            model_name='listadopagos',
            name='promocion_id',
            field=models.IntegerField(default=1),
        ),
    ]
