# Generated by Django 2.1.2 on 2018-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0022_auto_20181111_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='entre_calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='id',
            field=models.AutoField(help_text='Id único para transportista ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
