# Generated by Django 2.1.2 on 2018-11-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_natagua', '0024_auto_20181112_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(help_text='Id único para Profesor ', primary_key=True, serialize=False)),
                ('apellido', models.CharField(db_index=True, max_length=100)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('dni', models.CharField(max_length=25, unique=True)),
                ('edad', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'MUJER'), ('H', 'HOMBRE')], db_index=True, max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('entre_calle', models.CharField(blank=True, max_length=200, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidad_profesor', to='app_natagua.Localidad')),
                ('id_provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_profesor', to='app_natagua.Provincia')),
            ],
            options={
                'verbose_name_plural': 'Profesor',
                'ordering': ('apellido', 'nombre'),
            },
        ),
        migrations.AlterModelOptions(
            name='transportista',
            options={'ordering': ('apellido', 'nombre'), 'verbose_name_plural': 'Transportista'},
        ),
        migrations.AlterField(
            model_name='transportista',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='fecha_nacimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='profesor',
            index=models.Index(fields=['apellido', 'nombre'], name='prof_apellido_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='profesor',
            index=models.Index(fields=['apellido', 'dni'], name='prof_apellido_dni'),
        ),
    ]
